Documentation on how to publish asset through the UI
agera-edc/MinimumViableDataspaceOld pull request #116
Opened 2022-05-09 10:14 UTC by cpeeyush

Documentation on how to publish asset through the UI

Closes #9 

Waiting for https://github.com/agera-edc/EDCDataDashboard/issues/16. Will publish PR after that.

2022-05-09 12:11 UTC, marcgs commented on docs/user/publish-asset.md
> +* Go to`Contract Definition Editor` pane and here you will see any existing contract definitions if any.
This item will be renamed to `Contract Definitions` in https://github.com/agera-edc/EDCDataDashboard/issues/16

2022-05-09 12:12 UTC, marcgs commented on docs/user/publish-asset.md
> +        *Add an asset selector in the UI box named `Selector`. e.g. `asset:prop:id = test-document`
This part will be reworked in https://github.com/agera-edc/EDCDataDashboard/issues/16. I suggest we wait for this story and we revisit this documentation. I can take over this.

2022-05-09 13:22 UTC, zeier requested changes
Let's move the documentation for the EDC Data Dashboard over to `docs/developer`, see https://github.com/agera-edc/MinimumViableDataspace/pull/101#issuecomment-1121043688

2022-05-10 07:31 UTC, cpeeyush commented
> Let's move the documentation for the EDC Data Dashboard over to `docs/developer`, see [#101 (comment)](https://github.com/agera-edc/MinimumViableDataspace/pull/101#issuecomment-1121043688)

Done.

2022-05-10 09:26 UTC, marcgs approved these changes

2022-05-11 06:55 UTC, pkirch approved these changes
LGTM! Minor comments.

2022-05-11 06:55 UTC, pkirch commented on docs/developer/publish-asset.md
> +* Click on `Create Contract Definition` button and this will open an UI popup where you can add further details.
nit: typo

```suggestion
* Click on `Create Contract Definition` button and this will open a UI popup where you can add further details.
```

2022-05-11 06:55 UTC, pkirch commented on docs/developer/publish-asset.md
> +* More than one asset selectors can be added.
Showing my ignorance here. However, I cannot follow those two steps in combination with the statement `asset selector which defines the assets that are being published` above.

Are there two ways to define assets which should be published?

1. Once by selecting assets as it is written in `Select the assets you want to add to the contract definition` AND
2. additionally by choosing the `asset selector`?

2022-05-11 07:25 UTC, zeier approved these changes
Let's include a screenshot of the UI, which is makes it much easier to follow the instructions and comprehend the process, even if you have not yet deployed your MVD instance. This way, you can read through the docs once, and easily remember what to do when you fire up the data dashboard.

Regarding the docs folder, it would make sense to have all the documentation for the EDC Data Dashboard in a dedicated folder e.g. docs/developer/edc-data-dashboard, since we will have multiple files and folders related to other topics in the docs/developer folder.

I created a corresponding story https://github.com/agera-edc/MinimumViableDataspace/issues/133 for this, let's keep the docs where they are for now and move them later as part of this follow-up story.

2022-05-11 07:25 UTC, zeier commented on docs/user/publish-asset.md
> +## Publishing an asset
If we add a couple of screen shots (once the UI changes are in) it would be easier to follow the description, and the reader could comprehend how a data transfer works without the need to deploy an MVD instance.

2022-05-11 07:25 UTC, zeier commented on docs/user/publish-asset.md
> +* Go to`Contract Definition Editor` pane and here you will see any existing contract definitions if any.
```suggestion
* Go to`Contract Definition Editor` pane and here you will see any existing contract definitions, if any.
```

2022-05-11 07:25 UTC, zeier commented on docs/user/publish-asset.md
> +        *Add a unique ID e.g. UUID for the contract definition in UI box named `ID`.
Formatting issue (bullet points are displayed as asterisks).

2022-05-11 07:25 UTC, zeier commented on docs/developer/publish-asset.md
> +Publishing an asset in EDC is done by creating a new contract definition. Every contract definition has an access policy and contract policy associated with it. Along with this it also has at least o
It would be good to describe how the parameters that can be entered on the UI translate to the API, as there is no asset selector to be defined (manually) when publishing an asset.

2022-05-11 07:25 UTC, zeier commented on docs/developer/publish-asset.md
> +* More than one asset selectors can be added.
```suggestion
  * More than one asset can be added to a contract definition.
```

2022-05-12 13:04 UTC, cpeeyush commented on docs/user/publish-asset.md
> +* Go to`Contract Definition Editor` pane and here you will see any existing contract definitions if any.
Applied.

2022-05-12 13:06 UTC, cpeeyush commented on docs/user/publish-asset.md
> +        *Add a unique ID e.g. UUID for the contract definition in UI box named `ID`.
Updated.

2022-05-12 13:46 UTC, cpeeyush commented on docs/user/publish-asset.md
> +## Publishing an asset
Done.

2022-05-12 13:47 UTC, cpeeyush commented on docs/developer/publish-asset.md
> +Publishing an asset in EDC is done by creating a new contract definition. Every contract definition has an access policy and contract policy associated with it. Along with this it also has at least o
Addressed. Updated the doc.

2022-05-12 13:49 UTC, cpeeyush commented on docs/developer/publish-asset.md
> +* More than one asset selectors can be added.
Updated the doc to make it clearer.

An end user just needs to select one or more assets which needs to be published with given contract definitions.

2022-05-12 13:49 UTC, merged