Feature/114 ci docker compose test
agera-edc/MinimumViableDataspaceOld pull request #134
Opened 2022-05-11 07:48 UTC by algattik

2022-05-11 15:50 UTC, algattik commented on system-tests/docker-compose.yml
> -version: '3.8'
Recommendation from docker-compose developers is to stick to (fully supported) version 2 if not using swarm mode. This is required to support the `depends_on` clause.

2022-05-13 12:40 UTC, cpeeyush commented on launcher/Dockerfile
> +RUN apt update && apt install curl -y && rm -rf /var/cache/apt/archives /var/lib/apt/lists
nit: just curious to understand why remove these directories `rm -rf /var/cache/apt/archives /var/lib/apt/lists`? If it adds some specific benefit then maybe consider adding a short comment about it. Thanks

2022-05-13 19:13 UTC, algattik commented on launcher/Dockerfile
> +RUN apt update && apt install curl -y && rm -rf /var/cache/apt/archives /var/lib/apt/lists
Added comment

2022-05-18 16:46 UTC, ouphi commented on system-tests/README.md
> +In the file, add the application client secret value under the `EDC_VAULT_CLIENTSECRET` key.
I find this name ` EDC_VAULT_CLIENTSECRET`a bit confusing.
Can't we call it `APP_CLIENT_SECRET` and explain here that it will be used to access the vault?

2022-05-18 17:40 UTC, ouphi requested changes
The following instructions are missing in the readme: `az login` and give the `azure keyvault secret officer` role to the logged in user.

2022-05-19 03:17 UTC, algattik commented on system-tests/README.md
> +In the file, add the application client secret value under the `EDC_VAULT_CLIENTSECRET` key.
Great idea, fixed

2022-05-19 03:17 UTC, algattik commented
> The following instructions are missing in the readme: `az login` and give the `azure keyvault secret officer` role to the logged in user.

Great catch! Fixed

2022-05-19 19:24 UTC, marcgs commented
Great job! Please have a look at #153 for an addition to support remote debugging.

2022-05-19 19:24 UTC, marcgs approved these changes

2022-05-19 20:21 UTC, ouphi approved these changes

2022-05-20 04:32 UTC, merged