Feature: run MVD locally
agera-edc/MinimumViableDataspaceOld pull request #152
Opened 2022-05-19 10:31 UTC by paullatzelsperger

2022-05-19 11:52 UTC, algattik requested changes
I'd like to understand why we need an additional setup to the existing docker-compose one.

See also https://github.com/agera-edc/MinimumViableDataspace/pull/13 where we have usability improvements also ensure the docker-compose setup is tested in CI.

2022-05-19 11:52 UTC, algattik commented on .github/actions/gradle-setup/action.yml
> +        ref: main
we don't want that, we need a stable setup

2022-05-19 11:52 UTC, algattik commented on deployment/terraform/variables.tf
> +  default = "northeurope"
this will be used for policy rules later on. Why is this changed needed?

2022-05-19 11:52 UTC, algattik commented on deployment/terraform/variables.tf
> +  default     = "latest"
same comment as before

2022-05-19 11:52 UTC, algattik commented on docker-compose.yaml
> +# Docker-compose file to run MVD locally, for demo or debug purposes
redundant with docker-compose file in system-tests. Could we reuse?

2022-05-19 11:52 UTC, algattik commented on launcher/Dockerfile
> +#HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail -X GET http://localhost:8181/api/check/health || exit 1
why this change?

2022-05-19 11:52 UTC, algattik commented on docker-compose.yaml
> +          memory: "8g"
why such high resource needs?

2022-05-19 11:52 UTC, algattik commented on docker-compose.yaml
> +version: "3.9"
recommending to use version 2 for more functionality

2022-05-19 11:53 UTC, algattik commented
Could you work on a branch in agera-edc, so we could give OIDC permissions for the CI pipeline to run against azure?

2022-05-19 12:10 UTC, paullatzelsperger commented on .github/actions/gradle-setup/action.yml
> +        ref: main
as I mentioned in the PR description - ignore all changes to the CI files.

2022-05-19 12:10 UTC, paullatzelsperger commented on deployment/terraform/variables.tf
> +  default = "northeurope"
it isnt. as above.

2022-05-19 12:12 UTC, paullatzelsperger commented on launcher/Dockerfile
> +#HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail -X GET http://localhost:8181/api/check/health || exit 1
`curl` isn't contained in the `slim-buster` image, so the healthcheck always failed. I could have added `apt update && apt install curl -y`, but chose to deactivate the healthcheck, as it didn't offer any value for local debugging/testing.

2022-05-19 13:34 UTC, paullatzelsperger commented on docker-compose.yaml
> +# Docker-compose file to run MVD locally, for demo or debug purposes
Those seem to be different enough that I would argue that it makes sense to have them both.

2022-05-19 17:31 UTC, marcgs commented
FYI We have a feature with 2 stories for the local setup in the backlog: https://github.com/agera-edc/MinimumViableDataspace/issues/53. IMO it could be easier to have the possibility to remote debug EDC the containers instead of creating separate IntelliJ run configurations.

I have opened a PR to allow remote debugging in the current existing docker compose file for the system tests: https://github.com/agera-edc/MinimumViableDataspace/pull/153

2022-05-20 04:35 UTC, algattik commented on launcher/Dockerfile
> +#HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail -X GET http://localhost:8181/api/check/health || exit 1
Just merged #134 - the health check is useful there with docker-compose file v2 (not v3) to have a container wait for another

2022-05-20 04:42 UTC, algattik commented on docker-compose.yaml
> +      - company1.env
where is this file?

2022-05-20 04:42 UTC, algattik commented on docker-compose.yaml
> +# Docker-compose file to run MVD locally, for demo or debug purposes
What does this new file bring in addition to the old one?

2022-05-23 06:42 UTC, algattik commented
Thanks a lot, we've taken the main items into #153 and #156, I think we can now close this?

2022-05-24 06:15 UTC, marcgs commented
Thanks a lot for the effort Paul! I agree with @algattik that it would be good not to duplicate the `docker-compose` from the one we already have to run system tests, and which gets constantly validated in CI.  I think one of the main painpoints of the local setup with this approach is to create the `.env` configuration, which was improved by #134 where these env files are automatically on deployment, and can be copied over from the [artefacts](https://github.com/agera-edc/MinimumViableDataspace/actions/runs/2368825384) (see testing configuration). I think this spike can be closed as AFAIS all relevant changes have been merged into the repo.

2022-05-30 13:40 UTC, closed without merging