Feature/181 use registration service endpoint to fetch participants
agera-edc/MinimumViableDataspaceOld pull request #210
Opened 2022-06-08 12:35 UTC by Izzzu

Use Registration Service endpoint instead of shared json files to fetch participants. 

- Publish Registration Service locally in CD
- Update version of deployed Registration Service 
- Add registration_service_url to terraform variables
- Pass registration service url as environment variable in docker compose
- Clean up registry json files
- Add instructions to readme how to publish Registration Service locally
- Update ADR: https://github.com/agera-edc/MinimumViableDataspace/tree/main/docs/developer/decision-records/2022-04-28-federated-catalog
- Change json based FederatedCacheNodeDirectory to RegistrationServiceNodeDirectory that uses Registration Service API as a backend

Closes agera-edc/MinimumViableDataspaceFork#49

2022-06-09 11:28 UTC, algattik commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectoryExtension.java
> +        var registrationServiceApiUrl = ConfigurationFunctions.propOrEnv("REGISTRATION_SERVICE_API_URL", API_URL);
```suggestion
        var registrationServiceApiUrl = ConfigurationFunctions.propOrEnv("registration.service.api.url", API_URL);
```

should automatically map to `REGISTRATION_SERVICE_API_URL` env var

2022-06-09 11:30 UTC, algattik commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectory.java
> +    private final RegistryApi api;
```suggestion
    private final RegistryApi apiClient;
```

2022-06-09 11:36 UTC, algattik requested changes

2022-06-09 11:36 UTC, algattik commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectory.java
> +    private FederatedCacheNode map(Participant participant) {
```suggestion
    private FederatedCacheNode mapParticipant(Participant participant) {
```

2022-06-09 11:36 UTC, algattik commented on extensions/refresh-catalog/src/test/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectoryTest.java
> +        assertThat(cacheNodes).extracting(FederatedCacheNode::getSupportedProtocols).containsExactlyInAnyOrder(company1.getSupportedProtocols(), company2.getSupportedProtocols());
would this be clearer and also more robust
```
assertThat(cacheNodes)
                .containsExactly(map(company1), map(company2), map(company3));
```

2022-06-09 11:36 UTC, algattik commented on system-tests/.env.example
> +REGISTRATION_SERVICE_URL=<registration-service-api-url>
```suggestion
REGISTRATION_SERVICE_URL=<registration-service-url>
```

2022-06-09 11:36 UTC, algattik commented on system-tests/README.md
> +One of the MVD dependencies is Registration Service rest client library. Registration Service is not published to any central artifactory yet so in local
```suggestion
One of the MVD dependencies is the Registration Service REST client library. Registration Service is not published to any central artifactory yet so in local 
```

2022-06-09 11:36 UTC, algattik commented on system-tests/README.md
> +Follow [these instructions](https://github.com/agera-edc/RegistrationService/blob/main/docs/developer/openapi.md) to generate rest client.
this step is not needed, I believe. `./gradlew publishToMavenLocal`  will first build

2022-06-09 13:03 UTC, Izzzu commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectory.java
> +    private FederatedCacheNode map(Participant participant) {
To improve readability, I'd change it to 'toFederatedCacheNode'
then line 29 would be:
`api.listParticipants().stream().map(this::toFederatedCacheNode).collect(Collectors.toList());`

instead of 
`return api.listParticipants().stream().map(this::mapParticipant).collect(Collectors.toList());`

because it's visible from the argument that we are mapping Participant.
what do you think?

2022-06-09 13:27 UTC, algattik commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectory.java
> +    private FederatedCacheNode map(Participant participant) {
sure anything works :)

2022-06-09 13:56 UTC, Izzzu commented on extensions/refresh-catalog/src/test/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectoryTest.java
> +        assertThat(cacheNodes).extracting(FederatedCacheNode::getSupportedProtocols).containsExactlyInAnyOrder(company1.getSupportedProtocols(), company2.getSupportedProtocols());
it doesn't seem to work because FederatedCacheNode doesn't have `equals` and `hashCode` overridden

2022-06-09 14:01 UTC, Izzzu commented on extensions/refresh-catalog/src/main/java/org/eclipse/dataspaceconnector/mvd/RegistrationServiceNodeDirectory.java
> +    private final RegistryApi api;
done

2022-06-09 15:38 UTC, algattik approved these changes

2022-06-10 09:05 UTC, marcgs commented on .github/workflows/deploy.yaml
> +          REGISTRATION_SERVICE_URL=${{ needs.Deploy-Dataspace.outputs.registration_service_url }}
Why is this field not set in https://github.com/agera-edc/MinimumViableDataspace/actions/runs/2467355035 ?

2022-06-10 09:10 UTC, marcgs commented on system-tests/docker-compose.yml
> +      REGISTRATION_SERVICE_API_URL: ${REGISTRATION_SERVICE_URL}/api
We are appending `/api` in many places. Wouldn't it be better to export directly a REGISTRATION_SERVICE_API_URL variable from terraform?

2022-06-10 09:44 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +files as a data source and exposes the data via REST API.
Json files are not used anymore as PR https://github.com/agera-edc/RegistrationService/pull/5 already merged to use in-memory store.
```suggestion
The deployment pipeline deploys one instance of Registration Service in MVD set up. The Registration Service stores data in-memory and exposes the data via REST API.
```

2022-06-10 09:48 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +#### Json files as data source
this also needs to be updated. As Json files will not be used as mentioned in above comment. We can decide internally if we do this update here or in a separate PR when we remove infra related to shared json files.
//cc @algattik (Adding you here as you plan to do the infra change next)

2022-06-10 10:03 UTC, algattik commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +#### Json files as data source
Actually as of this PR JSON files are still used as store

2022-06-10 10:12 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +#### Json files as data source
@algattik But in-memory PR is already merged https://github.com/agera-edc/RegistrationService/pull/5 so that's why registration service will not use JSON files for storage. Correct ?

2022-06-10 10:21 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +#### Json files as data source
or maybe we as scope of this PR regisration service will still read from json files as we checkout registration service to a git hash which is before in-memory store implementation PR.

So this can be updated later. No change needed . thanks.

2022-06-10 10:21 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-28-federated-catalog/README.md
> +files as a data source and exposes the data via REST API.
Discard. Thank you.
See comment below.

2022-06-10 10:33 UTC, cpeeyush approved these changes

2022-06-10 11:47 UTC, marcgs approved these changes

2022-06-10 15:36 UTC, Izzzu commented on system-tests/docker-compose.yml
> +      REGISTRATION_SERVICE_API_URL: ${REGISTRATION_SERVICE_URL}/api
It's more consistent with other output variables, eg. webapp_url
Also it's more generic in case we would need to use registration url in different context than just api. At some point we would probably need to add a version to the api url anyway.
I would leave it like that for now but we can discuss

2022-06-10 16:14 UTC, merged