Registry Service DID
agera-edc/MinimumViableDataspaceOld pull request #211
Opened 2022-06-08 16:25 UTC by cpeeyush

- Adds Well-known DID endpoint for registration service during deployment.

Closes #185

2022-06-09 11:15 UTC, algattik commented on .github/workflows/deploy.yaml
> +          echo "DID_HOST=$DID_HOST" >> $GITHUB_ENV
nit: for consistency we could use `set-output` here and `{{ steps.runterraform.outputs.did_host }}` further down

2022-06-09 11:17 UTC, algattik commented on deployment/terraform/dataspace/main.tf
> +        "serviceEndpoint" : "http://dummy"
why add this block with dummy URL? the authority will not have an IH anyway, AFAIK

2022-06-09 11:25 UTC, cpeeyush commented on deployment/terraform/dataspace/main.tf
> +        "serviceEndpoint" : "http://dummy"
As per the spec it has an identity hub. https://github.com/Metaform/mvd/blob/main/registration-service/registration-service-tech-spec.md

2022-06-09 11:25 UTC, algattik requested changes
comment inline

2022-06-09 11:27 UTC, algattik commented on .github/workflows/deploy.yaml
> +          echo "DID_HOST=$DID_HOST" >> $GITHUB_ENV
for consistency with https://github.com/agera-edc/MinimumViableDataspace/pull/210/files, consider using an output here instead (`set-output`)

2022-06-09 12:55 UTC, marcgs commented on deployment/terraform/dataspace/main.tf
> +        "serviceEndpoint" : "http://dummy"
AFAIK there is no explicit requirement for any authorization against the Registry Service so far, which would be the only reason to have an Identity Hub. To keep things simple for the MVD I would leave it out.

2022-06-10 07:57 UTC, cpeeyush commented on deployment/terraform/dataspace/main.tf
> +        "serviceEndpoint" : "http://dummy"
okay as per the discussion I have removed it.

2022-06-10 08:35 UTC, algattik commented on deployment/terraform/dataspace/main.tf
> +    "@context" = ["https://www.w3.org/ns/did/v1",
nit

```suggestion
    "@context" = [
    "https://www.w3.org/ns/did/v1",
```

2022-06-10 08:36 UTC, algattik approved these changes

2022-06-10 09:33 UTC, cpeeyush commented on .github/workflows/deploy.yaml
> +          echo "DID_HOST=$DID_HOST" >> $GITHUB_ENV
updated.

2022-06-10 11:27 UTC, marcgs approved these changes

2022-06-10 11:58 UTC, merged