ADR on Web DID
agera-edc/MinimumViableDataspaceOld pull request #39
Opened 2022-04-11 15:03 UTC by marcgs

Document Web DID usage for MVD.

2022-04-11 15:36 UTC, cpeeyush reviewed
Added feedback.

2022-04-11 15:36 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +- KeyVault for storing certificates
nit: 
Just a question (not need to make a change):

To begin with do we also need to have storage account and key vault for every connector, or we can share a common storage + key vault between connectors? Or do you think that will make it more complex in terms of destroying a connector infra+ other management?

2022-04-11 15:36 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +An automated terraform deployment should generate certificates, DID documents and deploy these Azure components for each connector instance automatically.
Maybe it is a good to also add sample DID documents json here and explain a bit about it. It will be helpful to set more context.

2022-04-11 15:36 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +An automated terraform deployment should generate certificates, DID documents and deploy these Azure components for each connector instance automatically.
`each connector instance automatically` - automatically or you want to say part of CI/CD flow ?

2022-04-11 15:36 UTC, cpeeyush commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +A JWT token is sent on each IDS request. The JWT is generated using the private key in the certicate available in the KeyVault of the consumer connector. The DID is set as issuer of the JWT token, wh
Maybe it is good to have a sample IDS request with JWT token (highlighting it) and adding further details about it where necessary, it will be better to set the context and a common understanding that what/how we want to achieve.

2022-04-11 16:40 UTC, algattik requested changes
1. Could we have an introduction with
- an introduction to the topic 
- links to the relevant documents (e.g. DID Web spec, Identity Hub spec)
- nomenclature and definitions

2. How can we maintain these PNG files? Any issue with using mermaid diagrams?
Why not use sequence diagrams for showing interaction sequences?

3. Could we avoid/reduce the use of passive voice for clarity?

Also pushed some style fixes

2022-04-12 07:35 UTC, chrislomonico commented
> 2\. How can we maintain these PNG files? Any issue with using mermaid diagrams?
>     Why not use sequence diagrams for showing interaction sequences?

My perspective on this:
- The PNG's for this stage are fine, as a stretch, time permitting they can be migrated; I do not see much of a point in spending too much time on this
- We do not use Mermaid, we have the option with github to work with https://app.[diagrams.net](https://app.diagrams.net/)/ (formerly known as draw.io)

2022-04-12 08:18 UTC, marcgs commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +- KeyVault for storing certificates
I think the closest to a real scenario is to have a Storage Account & Keyvault for each connector instance. It is not more effort than having a common one, quite the contrary IMO, I think it will simplify things as we can completely wipe things out if the connector is removed.

2022-04-12 09:44 UTC, marcgs commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +An automated terraform deployment should generate certificates, DID documents and deploy these Azure components for each connector instance automatically.
I added references to sample DID documents in the spec, as well as a reference to the template in edc-showcase

2022-04-12 09:48 UTC, marcgs commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +An automated terraform deployment should generate certificates, DID documents and deploy these Azure components for each connector instance automatically.
rephrased 👍🏻

2022-04-12 13:34 UTC, algattik approved these changes
nit: a short explanation of what a did document is would be helpful

2022-04-12 14:20 UTC, cpeeyush approved these changes
Good work.

2022-04-12 15:57 UTC, marcgs commented on docs/developer/decision-records/2022-04-11-decentralized-identity/README.md
> +A JWT token is sent on each IDS request. The JWT is generated using the private key in the certicate available in the KeyVault of the consumer connector. The DID is set as issuer of the JWT token, wh
Unfortunately I could not find IDS request samples. The implementation to add JWTs in the header is already available in EDC and we won't need to implement anything in this area.

2022-04-12 16:01 UTC, merged